---
- name: Add peer to WireGuard server
  hosts: _personal_wireguard_server
  become: true
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: 'us-east-1'
    ansible_aws_ssm_bucket_name: personal-ansible-ssm-transfers
    wireguard_interface: "wg1"
    base_ip: "10.0.0"
    client_ip: "{{ base_ip }}.2"
    peer_public_key: "{{ lookup('env', 'PEER_PUBLIC_KEY') }}"
    preshared_key: "{{ lookup('env', 'PRESHARED_KEY') }}"

  pre_tasks:
    - name: Check if environment variables are set
      fail:
        msg: "Environment variables PEER_PUBLIC_KEY and PRESHARED_KEY must be set."
      when: peer_public_key is none or peer_public_key == "" or preshared_key is none or preshared_key == ""

  tasks:
    - name: Add peer to WireGuard configuration
      blockinfile:
        path: "/etc/wireguard/{{ wireguard_interface }}.conf"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ client_ip }}"
        block: |
          [Peer]
          PublicKey = {{ peer_public_key }}
          PresharedKey = {{ preshared_key }}
          AllowedIPs = {{ client_ip }}/32

    - name: Restart WireGuard service to apply changes
      systemd:
        name: "wg-quick@{{ wireguard_interface }}"
        state: restarted
