- name: Fetch Server Info and Generate WireGuard Peer Config
  hosts: _personal_wireguard_server
  become: true
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: 'us-east-1'
    ansible_aws_ssm_bucket_name: personal-ansible-ssm-transfers
    wireguard_port: 51820
  tasks:
    - name: Ensure curl is installed
      ansible.builtin.apt:
        name: curl
        state: present
    - name: Fetch IMDSv2 token
      ansible.builtin.command: 'curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"'
      register: imdsv2_token
      changed_when: false
    - name: Fetch Public IP of the EC2 instance using IMDSv2 token
      ansible.builtin.command: 'curl -H "X-aws-ec2-metadata-token: {{ imdsv2_token.stdout }}" http://169.254.169.254/latest/meta-data/public-ipv4'
      register: public_ip
      changed_when: false
    - name: Fetch WireGuard Public Key
      ansible.builtin.command: 'cat /etc/wireguard/public.key'
      register: wireguard_public_key
      changed_when: false
    - name: Display Public IP
      ansible.builtin.debug:
        msg: "The public IP of the EC2 instance is: {{ public_ip.stdout }}"
    - name: Display WireGuard Public Key
      ansible.builtin.debug:
        msg: "The WireGuard server public key is: {{ wireguard_public_key.stdout }}"
    - name: Display WireGuard Peer Config With Public IP
      ansible.builtin.debug:
        msg:
          - "[Peer]"
          - "PublicKey = {{ wireguard_public_key.stdout }}"
          - "Endpoint = {{ public_ip.stdout }}:{{ wireguard_port }}"
