- name: Restart WireGuard Service on Server
  hosts: _personal_wireguard_server
  become: true
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: 'us-east-1'
    ansible_aws_ssm_bucket_name: personal-ansible-ssm-transfers
    wireguard_interface: "wg1" # You can change this to wg0, wg2, etc.
  tasks:
    - name: Restart WireGuard Service
      ansible.builtin.systemd:
        name: "wg-quick@{{ wireguard_interface }}"
        state: restarted
- name: Restart WireGuard Service on Local Client
  hosts: localhost
  become: true
  connection: local
  vars:
    wireguard_interface: "wg1" # You can change this to wg0, wg2, etc.
  tasks:
    - name: Restart WireGuard Service
      ansible.builtin.systemd:
        name: "wg-quick@{{ wireguard_interface }}"
        state: restarted
